import { Investigator } from "../types";

const investigators: Investigator[] = [
    {
        id: "1",
        name: "Kate Winthrop",
        title: "The Scientist",
        ability: "Science!",
        abilityDescription:
            "Monsters cannot appear during Kate's turn. In addition, she is immune to all Terror effects",
        startingItems: "Spell, Unique",
        sanity: 6,
        maxSanity: 6,
        stamina: 4,
        maxStamina: 4,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "2",
        name: "Sister Mary",
        title: "The Nun",
        ability: "Guardian Angel",
        abilityDescription:
            "Mary may ignore any lingering effects of Mythos cards. She may ignore locked dice icons during her turn, allowing her to add them to her die pool as normal. At the end of her turn, all locked dice return to their locked dice icons.",
        startingItems: "Common, Unique, Spell",
        sanity: 7,
        maxSanity: 7,
        stamina: 3,
        maxStamina: 3,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "3",
        name: "Gloria Goldberg",
        title: "The Author",
        ability: "Psychic Sensitivity",
        abilityDescription:
            "While attempting to resolve on Other World car, Gloria may add the yellow and red dice to her pool for free.",
        startingItems: "Common, Spell",
        sanity: 6,
        maxSanity: 6,
        stamina: 4,
        maxStamina: 4,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "4",
        name: "Bob Jenkins",
        title: "The Salesman",
        ability: "Shrewd Dealer",
        abilityDescription:
            "Each time Bob gains 1 or more common items after setup, he gains 1 extra common item",
        startingItems: "Common, Common, Unique",
        sanity: 4,
        maxSanity: 4,
        stamina: 6,
        maxStamina: 6,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "5",
        name: "Vincent Lee",
        title: "The Doctor",
        ability: "Physician",
        abilityDescription:
            "Once per day, at the start of any player's turn, Vincent may cause any 1 investigator of his choice (icluding himself) to regain 1 stamina",
        startingItems: "Common, Spell",
        sanity: 5,
        maxSanity: 5,
        stamina: 5,
        maxStamina: 5,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: true,
        usedDailyAbility: false,
        dailyAbility: "heal:stamina",
    },
    {
        id: "6",
        name: "Jenny Barnes",
        title: "The Dilettante",
        ability: "Trust Fund",
        abilityDescription:
            "At the start of her Resoulution phase, Jenny may discard 1 common item, clue token, or spell to add the yellow and red dice to her dice pool.",
        startingItems: "Common, Spell",
        sanity: 6,
        maxSanity: 6,
        stamina: 4,
        maxStamina: 4,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "7",
        name: "Amanda Sharpe",
        title: "The Student",
        ability: "Studious",
        abilityDescription:
            "During her turn, Amanda may complete any number of tasks per roll instead of only one.",
        startingItems: "2 of any combination (Common, Spell, Unique)",
        sanity: 5,
        maxSanity: 5,
        stamina: 5,
        maxStamina: 5,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "8",
        name: "Michael McGlen",
        title: "The Gangster",
        ability: "Strong Body",
        abilityDescription:
            "Once per roll during his turn, Michael may change 1 die showing a Terror result to a Peril result.",
        startingItems: "Common, Common",
        sanity: 3,
        maxSanity: 3,
        stamina: 7,
        maxStamina: 7,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "9",
        name: "Carolyn Fern",
        title: "The Psychologist",
        ability: "Psychology",
        abilityDescription:
            "Once per day, at the start of any player's turn, Carolyn may cause any 1 investigator of her choice (including herself) to regain 1 sanity.",
        startingItems: "Common, Unique",
        sanity: 6,
        maxSanity: 6,
        stamina: 4,
        maxStamina: 4,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: true,
        usedDailyAbility: false,
        dailyAbility: "heal:sanity",
    },
    {
        id: "10",
        name: "Darrell Simmons",
        title: "The Photographer",
        ability: "Hometown Advantage",
        abilityDescription:
            "Once per roll during his turn, Darrell may change the result of a die from 1 investigation to 2, from 2 investigations to 3, or (on yellow and red dice) from 3 investigations to 4.",
        startingItems: "Common, Unique",
        sanity: 4,
        maxSanity: 4,
        stamina: 6,
        maxStamina: 6,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "11",
        name: "Dexter Drake",
        title: "The Magician",
        ability: "Magical Gift",
        abilityDescription:
            "Each time Drake gains 1 or more spells after setup, he gains 1 extra spell.",
        startingItems: "Unique, Spell, Spell",
        sanity: 5,
        maxSanity: 5,
        stamina: 5,
        maxStamina: 5,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "12",
        name: "Monterey Jack",
        title: "The Archaeologists",
        ability: "Archaeology",
        abilityDescription:
            "Each time Monterey gains 1 or more unique items after setup, he gains 1 extra unique item.",
        startingItems: "Common, Unique, Unique",
        sanity: 3,
        maxSanity: 3,
        stamina: 7,
        maxStamina: 7,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "13",
        name: "Joe Diamond",
        title: "The Private Eye",
        ability: "Hunches",
        abilityDescription:
            "Each time Joe spends 1 clue token, he gains a second free reroll (as though he has spent a second clue token).",
        startingItems: "Common, Clue Token",
        sanity: 4,
        maxSanity: 4,
        stamina: 6,
        maxStamina: 6,
        clueTokens: 1,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "14",
        name: "Harvey Walters",
        title: "The Professor",
        ability: "Strong Mind",
        abilityDescription:
            "Once per roll during his turn, Harvey may change 1 die showing a Terror result to a Lore result.",
        startingItems: "Spell, Unique",
        sanity: 7,
        maxSanity: 7,
        stamina: 3,
        maxStamina: 3,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
    {
        id: "15",
        name: "Mandy Thompson",
        title: "The Researcher",
        ability: "Research",
        abilityDescription:
            "Once per day, after any player has rolled, Mandy may reroll 2 dice before determining if the active player was able to complete a task.",
        startingItems: "Common, Clue Token",
        sanity: 5,
        maxSanity: 5,
        stamina: 5,
        maxStamina: 5,
        clueTokens: 1,
        elderSigns: 0,
        hasDailyAbility: true,
        usedDailyAbility: false,
        dailyAbility: "roll:two-dice",
    },
    {
        id: "16",
        name: '"Ashcan" Pete',
        title: "The Drifter",
        ability: "Scrounge",
        abilityDescription:
            "Each time Pete gains 1 Common, Unique, or Spell after setup, he may choose to instead gain 1 Clue Token, Common, or Spell",
        startingItems: "Ally: Duke",
        sanity: 4,
        maxSanity: 4,
        stamina: 6,
        maxStamina: 6,
        clueTokens: 0,
        elderSigns: 0,
        hasDailyAbility: false,
        usedDailyAbility: false,
        dailyAbility: "none",
    },
];

export default investigators.sort((a, b) =>
    a.name.toLocaleLowerCase().localeCompare(b.name.toLowerCase())
);
